name: okapi_z
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_stripe: ^11.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.4
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.3.5
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

flutter:
  assets:
    - assets/images/
    - assets/icons/bottom_nav_bar/
    - assets/icons/
  uses-material-design: true

dependency_overrides:
  meta: ^1.15.0 # 호환 가능한 버전으로 강제 설정
